quarkus.http.host=127.0.0.1
quarkus.http.access-log.enabled=true
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title= File Storage Server
quarkus.http.body.handle-file-uploads=false
quarkus.log.level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.console.json=false
quarkus.package.jar.type=uber-jar
quarkus.http.limits.max-form-attribute-size=10M
fsserver.uploadedFilesPath=data-server

# Micrometer and Prometheus
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.http-client.enabled=true
quarkus.micrometer.binder.jvm.enabled=true
quarkus.micrometer.binder.system.enabled=true
